# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1tDd57GtqgysdPojUvFinHTR75S6pKg
"""

import numpy as np

marks = np.array([45, 39, 43, 44, 35])

average = np.mean (marks)

print("Average Marks:", average)

import numpy as np

temp = np.array([36, 38, 32, 31, 33, 38]) #solapur temp last 6 days

print("Maximum Temperature:", np.max(temp))

print("Minimum Temperature:", np.min(temp))

print("Average Temperature:", np.mean(temp))

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

import numpy as np

# Adding prompts to make input clearer
try:
    print("Enter rows and columns (e.g., 2 3):")
    line1 = input()
    rows, cols = map(int, line1.split())

    elements = []
    print(f"Enter the {rows * cols} elements (space-separated):")
    line2 = input()
    elements = list(map(int, line2.split()))

    if len(elements) != rows * cols:
        print(f"Error: Expected {rows * cols} elements, but got {len(elements)}.")
    else:
        array = np.array(elements).reshape(rows, cols)
        print("\nGenerated Array:")
        print(array)
        print("Dimensions:", array.ndim)
        print("Shape:", array.shape)
        print("Size:", array.size)
except ValueError as e:
    print("Input Error: Please ensure you enter the correct number of integers.")
    print("Details:", e)

import numpy as np

# Taking input for rows and columns
rows, cols = map(int, input().split())

# Example usage (optional)
print("Rows:", rows)
print("Columns:", cols)

import numpy as np

# Input matrices
print("Enter Matrix A (3x3):")
matrix_a = np.array([list(map(int, input().split())) for i in range(3)])

print("Enter Matrix B (3x3):")
matrix_b = np.array([list(map(int, input().split())) for i in range(3)])

# Addition
madd = matrix_a + matrix_b
print("\nAddition (A + B):")
print(madd)

# Subtraction
msub = matrix_a - matrix_b
print("\nSubtraction (A - B):")
print(msub)

# Multiplication (element-wise)
mmul = matrix_a * matrix_b
print("\nElement-wise Multiplication (A * B):")
print(mmul)

# Division (element-wise)
# Note: This will result in an error or 'inf' if any element in Matrix B is 0.
mdiv = matrix_a / matrix_b
print("\nElement-wise Division (A / B):")
print(mdiv)

import numpy as np

def get_3x3_array(name):
    print(f"Enter the elements for {name} (3 rows, 3 space-separated integers per row):")
    elements = []
    for i in range(3):
        row = list(map(int, input().split()))
        elements.append(row)
    return np.array(elements)

# 1. Input Format: Prompt user for two 3x3 arrays
arr1 = get_3x3_array("Array 1")
arr2 = get_3x3_array("Array 2")

# 2. Perform Stacking Operations
# Horizontal Stacking: Side-by-side
h_stack = np.hstack((arr1, arr2))

# Vertical Stacking: One below the other
v_stack = np.vstack((arr1, arr2))

# 3. Output Format: Display results
print("\nHorizontal Stack (side-by-side):")
print(h_stack)

print("\nVertical Stack (one below the other):")
print(v_stack)

import numpy as np

# Take user input for the start, stop, and step of the sequence
start = int(input("Enter start: "))
stop = int(input("Enter stop: "))
step = int(input("Enter step: "))

# Generate the sequence using np.arange()
a = np.arange(start, stop, step)

print(a)
# Print the generated sequence

import numpy as np

def array_operations(A, B):
    # Convert A and B to Numpy arrays
    A = np.array(A)
    B = np.array(B)

    # Arithmetic Operations
    sum_result = A + B
    diff_result = A - B
    prod_result = A * B

    # Statistical Operations
    mean_A = np.mean(A)
    median_A = np.median(A)
    std_dev_A = np.std(A)

    # Bitwise Operations
    and_result = A & B
    or_result = A | B
    xor_result = A ^ B

    return {
        "arithmetic": (sum_result, diff_result, prod_result),
        "stats": (mean_A, median_A, std_dev_A),
        "bitwise": (and_result, or_result, xor_result)
    }

import numpy as np

# Original array
inputList = list(map(int, input().split(" ")))
original_array = np.array(inputList)

# Create a view
view_array = original_array.view()

# Create a copy
copy_array = original_array.copy()

# Modify the view
view_array[0] = 99
print("Original array after modifying view:", original_array)
print("View array:", view_array)

# Modify the copy
copy_array[1] = 88
print("Original array after modifying copy:", original_array)
print("Copy array:", copy_array)